Import library Numpy

In [1]:
import numpy as np

## Soal nomor 1

In [4]:
A = np.array([[23,50],[7,12]])
B = np.array([[57,67],[99,43]])
C = np.array([[75,21],[57,12]])
D = np.array([[87,26],[18,84]])

In [7]:
tensor = np.array([[A,B],[C,D]])

In [18]:
tensor_1 = np.array([A,B])
tensor_2 = np.array([C,D])
tensorr = np.array([tensor_1,tensor_2])

In [19]:
tensorr == tensor

array([[[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]],


       [[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]]])

## Soal nomor 2

In [21]:
A = np.array([[23,50,19],
        [7,12,109],
        [57,67,98]])
B = np.array([17,22,19])

Dihasilkan vektor di ruang tiga dimensi real atau $\mathbb{R}^{3}$

In [27]:
A @ B 

array([1852, 2454, 4305])

Atau juga bisa dilakukan seperti ini, namun hasilnya berupa matriks $3\times1$ atau $\mathbb{R}^{3\times1}$

In [28]:
#Atau juga bisa dilakukan seperti ini, namun vektor yang dihasilkan berdimensi 3x1
A @ B.reshape(3,1)

array([[1852],
       [2454],
       [4305]])

## Soal nomor 3

In [29]:
A = np.array([[23,50,19],[7,12,109],[57,67,98]])

In [33]:
#Tranpose dari matriks A
A_transpose = A.transpose()
A_transpose

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [34]:
# Determinan dari matriks A
det_A = np.linalg.det(A)
det_A

131344.0000000002

In [37]:
# Inverse dari matriks A
inv_A = np.linalg.inv(A)
inv_A

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])